#============================================
#         Configs for localhost:
#============================================

#Datasourse props
spring:
  datasource:
    url: jdbc:mysql://84.0.0.31:3306/bike_championship?useUnicode=true&characterEncoding=utf8&useSSL=false&verifyServerCertificate=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop

#Jwt properties
jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000

#Cors constants
cors:
  origin: "*"
